export const UI_STRINGS = {
    chat: {
        noMessages: "No messages here yet.",
        startConversation: "Start the conversation!",
        messageTooOld: "This message is too old to be deleted",
        deleteConfirm: "Delete all messages in this room?",
        clearingChat: "Clearing messages...",
        deleteMessage: "Delete message",
        searching: "Searching...",
        loadingMessages: "Loading messages...",
        failedToLoad: "Failed to load messages",
        failedToSend: "Failed to send message",
        failedToDelete: "Failed to delete message",
    },
    sidebar: {
        messages: "Messages",
        searchPlaceholder: "Search...",
        directMessages: "Direct Messages",
        groupChats: "Group Chats",
        createGroup: "Create Group",
        noConversations: "No conversations yet",
        noConversationsHint: "Start by creating a group chat",
        noMessagesPreview: "No messages yet",
        loadingRooms: "Loading rooms...",
        unnamedGroup: "Unnamed Group",
        users: "Users",
        startConversation: "Start a conversation",
    },
    admin: {
        dashboardTitle: "Admin Dashboard",
        dashboardSubtitle: "Manage your tambayan",
        rooms: "Rooms",
        users: "Users",
        settings: "Settings",
        clearMessages: "Clear Messages",
        deleteGroup: "Delete Group",
        deleting: "Deleting...",
        deleteRoomConfirm: (name: string) => `Clear all messages in "${name}"?`,
        deleteGroupConfirm: (name: string) => `PERMANENTLY DELETE group "${name}"? This will clear all messages and remove the room for everyone.`,
        addNewRoom: "Add New Room",
        createRoom: "Create Room",
        creating: "Creating...",
        allRooms: (count: number) => `All Rooms (${count})`,
        noRooms: "No rooms found",
        personalChatLabel: "Personal Chat",
    },
    common: {
        loading: "Loading...",
        cancel: "Cancel",
        delete: "Delete",
        save: "Save",
        error: "Error",
        success: "Success",
        upload: "Upload",
        changePhoto: "Change Photo",
    },
    nicknames: {
        editNicknames: "Edit Nicknames",
        nickname: "Nickname",
        noNickname: "No nickname set",
        setNickname: "Set nickname",
        saveNickname: "Save",
        cancel: "Cancel",
        removeNickname: "Remove nickname",
        placeholder: "Enter nickname...",
        panelTitle: "Nicknames",
        editNicknameFor: (username: string) => `Edit nickname for ${username}`,
    },
    photos: {
        changeProfilePhoto: "Change Profile Photo",
        changeGroupPhoto: "Change Group Photo",
        uploading: "Uploading...",
        cropTitle: "Crop Layout",
        cropInstructions: "Drag to reposition, use slider to zoom. Final photo will be a 200x200 square.",
    }
};
