export const UI_STRINGS = {
    chat: {
        noMessages: "No messages here yet.",
        startConversation: "Start the conversation!",
        messageTooOld: "This message is too old to be deleted",
        deleteConfirm: "Delete all messages in this room?",
        clearingChat: "Clearing messages...",
        deleteMessage: "Delete message",
        searching: "Searching...",
        loadingMessages: "Loading messages...",
        failedToLoad: "Failed to load messages",
        failedToSend: "Failed to send message",
        failedToDelete: "Failed to delete message",
    },
    sidebar: {
        messages: "Messages",
        searchPlaceholder: "Search...",
        directMessages: "Direct Messages",
        groupChats: "Group Chats",
        createGroup: "Create Group",
        noConversations: "No conversations yet",
        noConversationsHint: "Start by creating a group chat",
        noMessagesPreview: "No messages yet",
        loadingRooms: "Loading rooms...",
        unnamedGroup: "Unnamed Group",
        users: "Users",
        startConversation: "Start a conversation",
    },
    admin: {
        dashboardTitle: "Admin Dashboard",
        dashboardSubtitle: "Manage your tambayan",
        rooms: "Rooms",
        users: "Users",
        settings: "Settings",
        clearMessages: "Clear Messages",
        deleting: "Deleting...",
        deleteRoomConfirm: (name: string) => `Delete all messages in "${name}"?`,
        addNewRoom: "Add New Room",
        createRoom: "Create Room",
        creating: "Creating...",
        allRooms: (count: number) => `All Rooms (${count})`,
        noRooms: "No rooms found",
    },
    common: {
        loading: "Loading...",
        cancel: "Cancel",
        delete: "Delete",
        save: "Save",
        error: "Error",
        success: "Success",
    }
};
