-- Create a table for public profiles
create table public.profiles (
  id uuid references auth.users not null primary key,
  username text unique not null,
  email text unique not null,
  is_admin boolean default false not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone." on public.profiles
  for select using (true);

create policy "Users can insert their own profile." on public.profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on public.profiles
  for update using (auth.uid() = id);

-- Create rooms table
create table public.rooms (
  id uuid default gen_random_uuid() primary key,
  slug text unique not null,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.rooms enable row level security;

create policy "Rooms are viewable by everyone." on public.rooms
  for select using (true);

-- Insert Lobby
insert into public.rooms (slug, name) values ('general', 'Lobby');

-- Create messages table
create table public.messages (
  id bigint generated by default as identity primary key,
  room_id uuid references public.rooms not null,
  user_id uuid references auth.users,
  sender_name text not null,
  content text not null,
  is_bot boolean default false not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.messages enable row level security;

create policy "Messages are viewable by everyone." on public.messages
  for select using (true);

create policy "Users can insert their own messages." on public.messages
  for insert with check (
    auth.role() = 'authenticated' AND 
    (auth.uid() = user_id OR is_bot = true)
  );

-- Function to handle new user signup and sync username from metadata
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, email)
  values (new.id, new.raw_user_meta_data->>'username', new.email);
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function on signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
